pipeline {
    agent any 
    stages {
        // stage('Checkout') {
        //     steps {
        //         // Checkout code from GitHub repository
        //         git 'https://github.com/edquestofficial/gen-ai-case-study.git'
        //     }
        // }
        stage('Run Python File') {
            steps {
                script {
                    // Run the Python file (change to your script's name)
                    sh 'python3 /home/ec2-user/jenkins/workspace/test_poc/research/04_architecture/index.py'
                }
            }
        }
    }
}
