name: AWS cdk app pipeline

on:
  push:        # Trigger workflow on push events
    branches:
      - cdk-poc   # Specify the branch to trigger the workflow (e.g., 'main')
  workflow_dispatch:
    inputs:
      DeployRegion:
        description: 'Dev Region'
        default: 'us-east-1'
        type: choice
        options:
          - us-east-1
          - us-west-2

jobs:
  cdk-app-scale-up:
    runs-on: ubuntu-latest
    environment: 'dev'
    env:
      ENVIRONMENT_NAME: 'infra-scale-up'
      ENVIRONMENT: 'dev'
      AWS_REGION: ${{ github.event.inputs.DeployRegion || 'us-east-1' }}


    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Setup AWS CLI
    - name: Setup python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Setup Node 18
    - name: Setup node 18
      uses: actions/setup-node@v3
      with:
        python-version: 18

    # Step 4: Install python dependencies
    # - name: Install python dependencies
    #   run: |
    #     pip install --upgrade pip
    #     pip install wheel


    # # Step 3: Setup AWS CLI
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v3
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1

    # # Step 3: Install dependencies
    # - name: Install dependencies
    #   run: |
    #     pip install --upgrade boto3 botocore

    # # Step 4: Deploy Lambda Function
    # - name: Create AWS Infra
    #   # run: python deploy_lambda.py
    #   # run: python D:\workspace\GenAI\github\gen-ai-case-study\research\04_architecture\create_aws_infra.py
    #   run: python research/04_architecture/create_aws_infra.py

    # # Step 5: Success Notification
    # - name: Notify success
    #   run: echo "AWS Lambda Function deployed successfully!"